patch: fix edk2 compile error
This patch which changes the way definitions are included in
nvme_internal.h is required in order to make EDK2 compile spdk
correctly.  The problem is, including this breaks the spdk native build.
So I can't compile spdk with this patch, and I can't compile edk2
without this patch.

Also with this final change edk2 compiles spdk successfully but then
fails to link with the following unresolved symbol.

Building ... /edk2/ShellPkg/Library/UefiShellDebug1CommandsLib/UefiShellDebug1CommandsLib.inf [X64]
/edk2/NetworkPkg/Library/DxeSpdkLib/SpdkShim/edk_sock.c:923:4: error: ‘struct spdk_net_impl’ has no member named ‘get_placement_id’
   .get_placement_id       = edk_sock_get_placement_id,
    ^~~~~~~~~~~~~~~~
This is because of the following upstream change in spdk. Upstream they
have removed the get_placement_id api from the spdk network library.
They've replaced it with a new api called "group_impl_get_optimal".

commit 5379aa95e7bc5acebb3e5bbcf17f812827805280
Author: Ben Walker <benjamin.walker@intel.com>
Date:   Thu Apr 1 13:07:17 2021 -0700

    sock: Each module now maintains its own sock_map

    This allows for different policies per module, as well as overlapped
    placement_id values.

    Change-Id: I0a9c83e68d22733d81f005eb054a4c5f236f88d9
    Signed-off-by: Ben Walker <benjamin.walker@intel.com>
    Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/7221
    Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
    Reviewed-by: Jim Harris <james.r.harris@intel.com>
    Reviewed-by: Aleksey Marchuk <alexeymar@mellanox.com>

diff --git a/include/spdk_internal/sock.h b/include/spdk_internal/sock.h
index 13249d007..d32ed0bab 100644
--- a/include/spdk_internal/sock.h
+++ b/include/spdk_internal/sock.h
@@ -84,6 +84,11 @@ struct spdk_sock_group_impl {
        STAILQ_ENTRY(spdk_sock_group_impl)      link;
 };

+struct spdk_sock_map {
+       STAILQ_HEAD(, spdk_sock_placement_id_entry) entries;
+       pthread_mutex_t mtx;
+};
+
 struct spdk_net_impl {
        const char *name;
        int priority;
@@ -109,7 +114,7 @@ struct spdk_net_impl {
        bool (*is_ipv4)(struct spdk_sock *sock);
        bool (*is_connected)(struct spdk_sock *sock);

-       int (*get_placement_id)(struct spdk_sock *sock, int *placement_id);
+       struct spdk_sock_group *(*group_impl_get_optimal)(struct spdk_sock *sock);
        struct spdk_sock_group_impl *(*group_impl_create)(void);
        int (*group_impl_add_sock)(struct spdk_sock_group_impl *group, struct spdk_sock *sock);
        int (*group_impl_remove_sock)(struct spdk_sock_group_impl *group, struct spdk_sock *sock);
@@ -300,8 +305,6 @@ spdk_sock_get_placement_id(int fd, enum spdk_placement_mode mode, int *placement
        }
 }

-extern struct spdk_sock_map g_map;
-

Signed-off-by: John Meneghini <jmeneghi@redhat.com>